name: Build, Tag, and Release

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19' # TODO: Take the go version as part of Environment available
    - name: Build project
      shell: bash
      run: |
        cd gocode/notes
        go build
    - name: Build tag
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag $BUILD_TAG -m "Tag $BUILD_TAG"
        git push origin $BUILD_TAG
    # - name: Create a Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: ./gocode/notes/notes
    #     tag_name: ${{ env.BUILD_TAG }}
    #     name: Release ${{ env.BUILD_TAG }}

# TODO: 
# - name: Release to GitHub Packages
#   uses: actions/upload-artifact@v3
#   with:
#     name: $BUILD_TAG
#     path: ./gocode/notes/notes
