name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Enter the build tag'
        required: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Store build tag as environment variable
        run: |
          echo "BUILD_TAG=${{ github.event.inputs.build_tag }}"
          echo "BUILD_TAG=${{ github.event.inputs.build_tag }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Run Golang build and tag workflow
        uses: ./.github/workflows/go/build
